language: c
dist: trusty
before_install:
  - sudo add-apt-repository ppa:dasom/ppa -y
  - sudo apt-get update
install:
  - sudo apt-get install -y build-essential devscripts equivs
  - echo y | sudo mk-build-deps -i -t apt-get
script:
 - ./autogen.sh --prefix=/usr
 - make
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bc70d4c138c5e1b3f32b
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
